# Generated by Django 3.0.2 on 2020-11-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('site_link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='project_images')),
            ],
        ),
    ]
